### ISSUE TITLE
Only works on root folder

### ISSUE THREAD

**Issue by derekperkins** [766b/vscode-go-outliner#4]
This is only showing types and functions for the root folder. I want to see them for whatever folder my currently open file is in.

**Comment by 766b** [comment]
Are you on Linux? I pushed a new version that fixes similar issue with Linux. Also there's slight issue with VS Code API where file change event does not fire sometimes, but it looks like it only happens on fresh instance and goes away if you open several files in series.

PS: It should change working directory based on current file (if there are valid .go files)

**Comment by derekperkins** [comment]
I am on Mac. I tried updating to 0.0.6 and am still seeing the same behavior. I tried both switching to open files and opening files in directories that were never open, and neither works.

Also, I am super excited for this extension, so thanks for the work writing and releasing it!

**Comment by 766b** [comment]
Did some changes, tried it on my old Mac, and it seems to work on root and sub-folders for me. Did the issue resolve itself for you?

**Comment by 766b** [comment]
Pushed new version, hopefully that fixes you issue. Also tested on Mac and it worked fine with latest version. If issue still persist, let me know.

**Comment by derekperkins** [comment]
It's working now. Thanks!
